name: CI with Allure and SonarQube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:   # 👈 esto permite ejecutarlo a mano



jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    env:
      NODE_ENV: test
      MONGO_URI_TEST: mongodb://localhost:27017/mydb
      JWT_SECRET: ${{ secrets.JWT_SECRET }}


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Newman, JMeter, Allure
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/apache-jmeter-5.6.3
          sudo ln -s /opt/apache-jmeter-5.6.3/bin/jmeter /usr/local/bin/jmeter
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Start backend in background
        run: |
          nohup npm run dev > backend.log 2>&1 &
          sleep 10


      - name: Verify backend is up
        run: curl --fail http://localhost:5000/api || (echo "API not responding" && exit 1)

      - name: Run unit tests with coverage
        run: npm test -- --coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov-report


      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Run JMeter test
        run: |
            jmeter -n -t test/"HTTP Request Defaults.jmx" -l test/results.jtl -e -o test/report
     
      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: test/report

      - name: Run Postman tests
        run: |
          newman run "test/All_API_Test.postman_collection.json" \
            --environment "test/Development.postman_environment.json" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export "test/postman-report.html"

      - name: Upload Postman HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: test/postman-report.html



      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      - name: Deploy to Vercel (Production)
        if: ${{ success() }}
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}



